@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container_Boundary(backend, "Servidor Backend (Python / Flask)") {
    Component(rotas, "Controlador de Rotas (API)", "Flask Route", "Recebe as requisições HTTP da tela.")
    Component(calculadora, "Módulo de Cálculos", "Python Class", "Aplica a regra do negócio (ex: transforma peso em kg para arrobas).")
    Component(repositorio, "Gerenciador de Dados", "SQLAlchemy / ORM", "Comunica-se com a base de dados SQL.")
}

ContainerDb(banco, "Banco de Dados", "SQLite", "Armazena os dados.")

Rel(rotas, calculadora, "Envia os dados de entrada para")
Rel(calculadora, repositorio, "Manda os dados calculados para")
Rel(repositorio, banco, "Executa comandos SQL em")

@enduml