@startuml DER_BoviMonitor
hide circle
skinparam linetype ortho

entity "PASTO" as pasto {
  * id_pasto : INT <<PK>>
  --
  nome_pasto : VARCHAR(50)
  capacidade_suportada : INT
}

entity "LOTE" as lote {
  * id_lote : INT <<PK>>
  --
  id_pasto : INT <<FK>>
  nome_lote : VARCHAR(50)
  quantidade_cabecas : INT
  categoria_animal : VARCHAR(30)
}

entity "MEDICAMENTO" as medicamento {
  * id_medicamento : INT <<PK>>
  --
  nome_medicamento : VARCHAR(100)
  tipo : VARCHAR(30)
  dias_carencia : INT
  obrigatorio_legal : BOOLEAN
}

entity "APLICACAO_MANEJO" as aplicacao {
  * id_aplicacao : INT <<PK>>
  --
  id_lote : INT <<FK>>
  id_medicamento : INT <<FK>>
  data_aplicacao : DATE
  data_liberacao_carencia : DATE
  dosagem : VARCHAR(20)
}

pasto ||--o{ lote : "abriga"
lote ||--o{ aplicacao : "recebe"
medicamento ||--o{ aplicacao : "é aplicado em"

@enduml
