@startuml Contexto_BoviMonitor
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(pecuarista, "Seu Osvaldo (Pecuarista)", "Dono da fazenda, acompanha alertas de carência e relatórios.")
Person(capataz, "Capataz / Gerente", "Registra manejo no curral e movimentação de lotes.")

System(boviMonitor, "BoviMonitor", "Sistema de controle sanitário, manejo de lotes e alertas de carência.")

System_Ext(orgaoFiscal, "Órgão Sanitário / Defesa Agropecuária", "Recebe comprovação de vacinas obrigatórias (ex: Aftosa).")


Rel(pecuarista, boviMonitor, "Consulta alertas, calendário e relatórios")
Rel(capataz, boviMonitor, "Cadastra lotes, vacinas e carência")
Rel(boviMonitor, orgaoFiscal, "Gera dados para declaração de vacinação")


@enduml
